15 error Error: Command failed: git remote update
15 error fatal: unable to access 'https://github.com/yat122/yat-util.git/': Failed to connect to github.com port 443: Timed out
15 error error: Could not fetch origin
15 error
15 error Fetching origin
15 error
15 error     at makeError (C:\Users\Administrator\AppData\Roaming\nvm\v12.13.1\node_modules\lerna\node_modules\execa\index.js:174:9)
15 error     at Function.module.exports.sync (C:\Users\Administrator\AppData\Roaming\nvm\v12.13.1\node_modules\lerna\node_modules\execa\index.js:338:15)
15 error     at Object.execSync (C:\Users\Administrator\AppData\Roaming\nvm\v12.13.1\node_modules\lerna\node_modules\@lerna\child-process\index.js:26:16)
15 error     at updateRemote (C:\Users\Administrator\AppData\Roaming\nvm\v12.13.1\node_modules\lerna\node_modules\@lerna\version\lib\is-behind-upstream.js:26:16)
15 error     at isBehindUpstream (C:\Users\Administrator\AppData\Roaming\nvm\v12.13.1\node_modules\lerna\node_modules\@lerna\version\lib\is-behind-upstream.js:11:3)
15 error     at VersionCommand.initialize (C:\Users\Administrator\AppData\Roaming\nvm\v12.13.1\node_modules\lerna\node_modules\@lerna\version\index.js:150:9)
